### ISSUE TITLE
Exclusion of channel 10 in MIDI files?

### ISSUE THREAD

**Issue by Holek** [qiao/euphony#1]
Hey, hey! First of all, wanted to say, that it's an awesome work you've done here!

I would like to ask you, maybe you know, if there is a possibility to exclude Channel 10 in MIDI files from being processed? Channel 10 is reserved for percussion, and when converted to just piano notes, doesn't make any sense.

I've discovered that, while I was fooling around with your script and trying out my own collection of MIDI files, so a demo is already up: http://pony.poltyn.com/euphony/#4

The original MIDI file: http://bit.ly/As2KqP

Once again, an amazing demo. :)

**Comment by qiao** [comment]
Done. BTW, I love canon too :)

**Comment by qiao** [comment]
@Holek You can now drag and drop your MIDI files onto the webpage. Enjoy !

 (You may clear the browser cache if the interface does not change)

**Comment by Holek** [comment]
Awww yeah!
